CREATE TABLE Community (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	isPrivate TINYINT(1) DEFAULT 1,
	description VARCHAR(1000),
	createdAt DATETIME NOT NULL DEFAULT NOW(),
	createdBy INT,
	updatedAt DATETIME,
	updatedBy INT,
	deletedAt DATETIME,
	CONSTRAINT PK_COMMUNITY PRIMARY KEY (id) 
)